# Generated by Django 5.2.8 on 2025-11-18 19:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('capacidad_maxima', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('activa', models.BooleanField(default=True, verbose_name='Sala Habilitada')),
            ],
            options={
                'verbose_name': 'Sala de Estudio',
                'verbose_name_plural': 'Salas de Estudio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona', models.CharField(max_length=12, verbose_name='RUT del Estudiante')),
                ('hora_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de Inicio')),
                ('hora_termino', models.DateTimeField(verbose_name='Hora de Término')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.sala', verbose_name='Sala Reservada')),
            ],
            options={
                'verbose_name': 'Reserva de Sala',
                'verbose_name_plural': 'Reservas de Salas',
                'ordering': ['-hora_inicio'],
            },
        ),
    ]
